travis:
  secure:
    BINSTAR_TOKEN: UkUOuJqeRFWWN6Low1O88GZFZk3r32GrOfdjwU254MbHeeF9Th7S0qWx1WV9iCq6x4CnvgOX9cdJCqu4Db6B/Sv2yvrVc1HKoeOHTYWTnwtrLcfMHCazTTnAxv92qTVLApx8c0tR3tZNdjwuuGYHMC/K6Q6M1xihqmjA1J4HGXVxBN0Q0q4nzt85527/fNGjJc5SY2Z15aGQCiWxpXBGdiyPiVKDiHVvlvKPoP0xQedKU+PJACrJbB1JGjG2SuPSh+Hlw7wv6Dz/EVwLm6vLBDpWuXyJEDrh8+HXvU7tQZWrm2pwJe7NBaJSEZGYOT6Vdft9st3Qh1FFRzmU6uSJTyIPybKEl2KFkaTZ/EWEZm5XC84iB1UTlSyuGb3Y/bd0adrARY8FEA8L9+zJfyQ5C4ery/rhy2Sh/fQ+HFKcb0U36YPK5Jr4NsP62nZj+2pe2+lNjNWEddN3AhmsAUDh2sIURyPsMstcxXfO1UF10G+/wpT2+nteKzQPPKpbv1Yzc2s5nKvFDyzeuwpkpMso2a/haV99TtS/qpCxypwIm5S0WXHMw841m/yriKp1lY0E9HGRxx/HKYn1k9ER/xPeqCe/m894y6BXWiVjNwjwpprB6sI8CMGxY0mAnfgZETEn2nopA82AspfbV3e/xMxAVdljDe6RdgHtNwWX1OJM+Rk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
