travis:
  secure:
    BINSTAR_TOKEN: cBQo/IHiXN9bFRkqQYR/CCsfhq4lO5sljwE3VzQGIYB00qqMjYjg2jTboeNwiQHvSRTGGMMgFHJ3wE0SZGRnmFQos6b/FOqrMw1gujqk7ynpYlaArWDPPRl7XySvADKUZC55vvCrhWuWl1sMfMDEM6/Pjsy7C96TrLIJZccysY708ebDDsfOFw/P7ozHmBxL+RTxPO75R8GyXXV3IMzDIE+9suHv0Q9NlZlAltlaQ603R60ux1nupumygtWMKhMbyWGjo8+9/aSUgNzb7zESqV69u/a47QGPghc4Jhm6oalNiZFnJlAtsGRWZwXWupTe2GfdNtqE6RAIxmGD5c8olLE6gFKoWFu7gue+mOcfgdAQpiddwzVL7haPhLhmfCjbBJZMmxIu8l5yOjNHm7IZTakex2iKFDvlBOzaGZGNmZZrgZpufHgO9pXplNN8sn1ic/NCUJZA8QwwrclJpNdyvh7yebk3PH9PowGeQ/3Eq8/sLxcs0O0P0k2Xgg3fNVtzN7u2OvUDsqJHlEsKLHYJIVQrryRtT8H5Igpj5kpMYkBAN0SFK4nYcheaXX+A09PTs2uIL7MfPS5M9VMQki5cXRZmMSNDI7qAVTMko4fG3EkKjCw4xC3wOFRppr+lB3TZhqprQLxjWPpmxF75EROF7Dky+nODsISbuXuUcp7O0oA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
